# Generated by Django 5.1.7 on 2025-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('HOUSE', 'Maison'), ('CATHEDRAL', 'Cathedrale'), ('CASTLE', 'Chateau')], max_length=20)),
            ],
        ),
    ]
