# Generated by Django 5.1.7 on 2025-04-02 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_construction_demolished'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construction',
            name='zip_code',
            field=models.CharField(default='Paris', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='The ZIP code you entered is not valid in France')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='construction',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('CATHEDRAL', 'Cathedral'), ('CASTLE', 'Castle')], max_length=20),
        ),
    ]
